# Generated by Django 5.2.8 on 2025-11-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='workout_name',
            new_name='name',
        ),
    ]
