# Generated by Django 5.2.8 on 2025-11-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_workout_name_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (Little or no exercise)'), ('light', 'Lightly Active (1 to 3 days/week)'), ('moderate', 'Moderately Active (3 to 5 days/week)'), ('active', 'Active (6 to 7 days/week)'), ('very_active', 'Very Active (Intense training / physical job)')], default='sedentary', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
