# Generated by Django 5.2.8 on 2025-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('core', 'Core')], default='chest', max_length=10),
        ),
    ]
